version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packages...
      - yarn global add @nestjs/cli
      - yarn install
      - yarn add -D @types/node
  build:
    commands:
      - echo Create build...
      - yarn build
  post_build:
    commands:
      - echo Nothing to do here...
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json