version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packages...
      - yarn install
  build:
    commands:
      - echo Create build...
      - yarn build
  post_build:
    commands:
      - echo Removing unnecessary files...
      - rm -rf node_modules/
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*